name: CD

on:
  push:
    branches: [main]          # deploy only what reaches main
  pull_request:
    branches: [main]
  workflow_dispatch:            # allow manual “Run workflow”

env:
  IMAGE_NAME: gradeclass-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gradeclass-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DH_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DH_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}